<a href="https://colab.research.google.com/github/andrheadennizecuyme/LinearAlgebra_2ndSem/blob/main/Assignment06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE
#Laboratory 5: Matrix Operations

#Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intermediate equations.
3. Apply matrix algebra in engineering solutions.

#Discussions


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


#Transposition
One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for a matrix $A$ its transpose is denoted as $A^T$. So for example:

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$

This can now be achieved programmatically by using `np.transpose()` or using the `T` method.

In [ ]:
A = np.array([
    [341, 9, 32],
    [8, -1, 00],
    [45, -90, 9]
])
A

array([[341,   9,  32],
       [  8,  -1,   0],
       [ 45, -90,   9]])

In [ ]:
AT1 = np.transpose(A)
AT1

array([[341,   8,  45],
       [  9,  -1, -90],
       [ 32,   0,   9]])

In [ ]:
AT2 = A.T
AT2

array([[341,   8,  45],
       [  9,  -1, -90],
       [ 32,   0,   9]])

In [ ]:
B = np.array([
    [9,8,7,6],
    [99,88,77,66],
])
B.shape

(2, 4)

In [ ]:
np.transpose(B).shape

(4, 2)

In [ ]:
B.T.shape

(4, 2)

In [ ]:
BT = B.T
BT

array([[ 9, 99],
       [ 8, 88],
       [ 7, 77],
       [ 6, 66]])

#Dot Product/Inner Product

The dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

We assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [ ]:
X = np.array([
    [6,3],
    [0,6]
])
Y = np.array([
    [-5,0],
    [9,9]
])

In [ ]:
np.array_equiv(X, Y)

False

In [ ]:
np.dot(X,Y)

array([[-3, 27],
       [54, 54]])

In [ ]:
X.dot(Y)

array([[-3, 27],
       [54, 54]])

In [ ]:
X @ Y

array([[-3, 27],
       [54, 54]])

In [ ]:
np.matmul(X,Y)

array([[-3, 27],
       [54, 54]])

In [ ]:
M = np.array([
    [1,7,4],
    [8,7,3],
    [2,7,0]
])
N = np.array([
    [-9,1,2],
    [5,3,5],
    [8,7,6]
])

In [ ]:
M @ N

array([[ 58,  50,  61],
       [-13,  50,  69],
       [ 17,  23,  39]])

In [ ]:
M.dot(N)

array([[ 58,  50,  61],
       [-13,  50,  69],
       [ 17,  23,  39]])

In [ ]:
np.matmul(M, N)

array([[ 58,  50,  61],
       [-13,  50,  69],
       [ 17,  23,  39]])

In [ ]:
np.dot(M, N)

array([[ 58,  50,  61],
       [-13,  50,  69],
       [ 17,  23,  39]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

Given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\6&-8\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\9&-9\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\8&8&8\\1&1&2\end{bmatrix}$$

In this case $A$ has a shape of $(4,2)$, $B$ has a shape of $(4,2)$ and $C$ has a shape of $(3,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [ ]:
X = np.array([
    [6, 99],
    [7, -7],
    [5, 8]
])
Y = np.array([
    [2,2],
    [4,4],
    [-88,-83]
])
Z = np.array([
    [0,7,7],
    [4,4,2]
])
print(X.shape)
print(Y.shape)
print(Z.shape)

(3, 2)
(3, 2)
(2, 3)


In [ ]:
X @ Z

array([[396, 438, 240],
       [-28,  21,  35],
       [ 32,  67,  51]])

In [ ]:
Y @ Z

array([[   8,   22,   18],
       [  16,   44,   36],
       [-332, -948, -782]])

The shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [ ]:
X @ Y.T

array([[  210,   420, -8745],
       [    0,     0,   -35],
       [   26,    52, -1104]])

In [ ]:
O = np.array([
    [8,55,4,0]
])
P = np.array([
    [1,1,1,-1]
])
print(O.shape)
print(P.shape)

(1, 4)
(1, 4)


In [ ]:
P.T @ O

array([[  8,  55,   4,   0],
       [  8,  55,   4,   0],
       [  8,  55,   4,   0],
       [ -8, -55,  -4,   0]])

In [ ]:
O @ P.T

And you can see that when you try to multiply A and B, it returns `ValueError` pertaining to matrix shape mismatch.

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [ ]:
A = np.array([
    [8,7,6],
    [6,7,8],
    [7,7,7]
])
B = np.array([
    [4,4,4],
    [2,4,8],
    [2,4,8]
])
C = np.array([
    [55,55,0],
    [0,55,55],
    [55,0,55]
])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
A.dot(np.eye(3))

array([[8., 7., 6.],
       [6., 7., 8.],
       [7., 7., 7.]])

In [ ]:
np.array_equal(A@B, B@A)

False

In [ ]:
E = A @ (B @ C)
E

array([[10670,  7810, 12100],
       [10890,  7590, 12540],
       [10780,  7700, 12320]])

In [ ]:
F = (A @ B) @ C
F

array([[10670,  7810, 12100],
       [10890,  7590, 12540],
       [10780,  7700, 12320]])

In [ ]:
np.array_equal(E, X)

False

In [ ]:
np.array_equiv(E, F)

True

In [ ]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
A @ E

array([[226270, 161810, 258500],
       [226490, 161590, 258940],
       [226380, 161700, 258720]])

In [ ]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(a_dot_z,z_mat)

True

In [ ]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

#Determinant

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
Thus we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [ ]:
A = np.array([
    [8,45],
    [0.0,99]
])
np.linalg.det(A)

791.9999999999994

In [ ]:
B = np.array([
              [7, -999, 1],
              [77, -99 ,-1],
              [777, -9, 1]
])
np.linalg.det(B)

928619.9999999992

In [ ]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [9,-63,5,6],
    [0,3,71,34],
    [93,81,8,2],
    [95,2,6,48]
])
np.linalg.det(B)

-20023739.999999978

#Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
That will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [ ]:
M = np.array([
    [0,13],
    [-99, 80]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
P = np.array([
              [9, 9, 0],
              [4, 2, -6],
              [8, 9, 7]
])
Q = np.linalg.inv(P)
Q

array([[-0.94444444,  0.875     ,  0.75      ],
       [ 1.05555556, -0.875     , -0.75      ],
       [-0.27777778,  0.125     ,  0.25      ]])

In [ ]:
P @ Q

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00, 0.00000000e+00],
       [3.33066907e-16, 0.00000000e+00, 1.00000000e+00]])

In [ ]:
## And now let's test your skills in solving a matrix with high dimensions:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [ ]:
squad = np.array([
    [2.0, 1.0, 1.5],
    [1.25, 1.0, 1.5],
    [1.75, 1.5, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade


array([[1.5 ],
       [1.35],
       [1.25]])

#ACTIVITY

##Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.

In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
P = np.array ([
    [9,7,5,3],
    [60,70,80,90],
    [0,0,0,0],
    [-2,4,-6,8]           
])
Q = np.array ([
    [1,-5,9,4],
    [4,1,5,9],
    [2,-3,1,7],
    [-4,2,9,1]           
])
R = np.array ([
    [55,65,70,75],
    [31,-13,81,-18],
    [3,9,9,12],
    [67,77,87,97]           
])

In [ ]:
S = Q.dot(P)
T = R.dot(S)
U = S.dot(R)
V = Q.dot(R)
W = P.dot(S)
X = Q + R
Y = S + P
Z = T + U

In [ ]:
print('PROPERTY 1')
{np.array_equiv(S,V)}
print('AB=BA')
print('Matrix AB:')
print(np.matmul(P,Q))
print('Matrix BA:')
print(np.matmul(Q,P))
print('APPROVED!')

PROPERTY 1
AB=BA
Matrix AB:
[[  35  -47  148  137]
 [ 140 -290 1780 1520]
 [   0    0    0    0]
 [ -30   48   68   -6]]
Matrix BA:
[[-299 -327 -419 -415]
 [  78  134   46  174]
 [-176 -168 -272 -208]
 [  82  116  134  176]]
APPROVED!


In [ ]:
print('PROPERTY 2')
{np.array_equiv(Q.dot(P),P.dot(S))}
print('A(BC)=(AB)C')
print('Matrix A(BC):')
print(np.matmul(Q,P))
print('Matrix (AB)C:')
print(np.matmul(P,S))
print('APPROVED!')

PROPERTY 2
A(BC)=(AB)C
Matrix A(BC):
[[-299 -327 -419 -415]
 [  78  134   46  174]
 [-176 -168 -272 -208]
 [  82  116  134  176]]
Matrix (AB)C:
[[ -2779  -2497  -4407  -3029]
 [-19180 -13240 -31620 -13520]
 [     0      0      0      0]
 [  2622   3126   3726   4182]]
APPROVED!


In [ ]:
print('PROPERTY 3')
{np.array_equiv(S.dot(R),Q)}
print('Matrix A(B+C)')
print(np.matmul(S,R))
print('Matrix (AB)+(AC):')
print(np.add(R,Q))
print('APPROVED!')

PROPERTY 3
Matrix A(B+C)
[[-55644 -50910 -87293 -61822]
 [ 20240  17140  31866  20868]
 [-29640 -27720 -46472 -33616]
 [ 20300  18580  31654  22742]]
Matrix (AB)+(AC):
[[ 56  60  79  79]
 [ 35 -12  86  -9]
 [  5   6  10  19]
 [ 63  79  96  98]]
APPROVED!


In [ ]:
print('PROPERTY 4')
{np.array_equiv(P.dot(S),Z)}
print('(B+C)A=(BA)+(CA)')
print('Matrix (B+C)A:')
print(np.matmul(P,S))
print('Matrix (BA)+(CA):')
print(np.add(S,Z))
print('APPROVED!')

PROPERTY 4
(B+C)A=(BA)+(CA)
Matrix (B+C)A:
[[ -2779  -2497  -4407  -3029]
 [-19180 -13240 -31620 -13520]
 [     0      0      0      0]
 [  2622   3126   3726   4182]]
Matrix (BA)+(CA):
[[ -73488  -63572 -116757  -75112]
 [  -5697  -10301   -6119  -14101]
 [ -30611  -27783  -48427  -33263]
 [  -1003    3741   -3409    7487]]
APPROVED!


In [ ]:
print('PROPERTY 5')
{np.array_equiv(Q.dot(1),V)}
print('A(1)=A')
print('Matrix A(1):')
print(np.multiply(Q,1))
print('Matrix A:')
print(Q)
print('APPROVED!')

PROPERTY 5
A(1)=A
Matrix A(1):
[[ 1 -5  9  4]
 [ 4  1  5  9]
 [ 2 -3  1  7]
 [-4  2  9  1]]
Matrix A:
[[ 1 -5  9  4]
 [ 4  1  5  9]
 [ 2 -3  1  7]
 [-4  2  9  1]]
APPROVED!


In [ ]:
print('PROPERTY 6')
{np.array_equiv(P.dot(0),0)}
print('A(0)=0')
print('Matrix A(0):')
print(np.multiply(P,0))
print('APPROVED!')

PROPERTY 6
A(0)=0
Matrix A(0):
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
APPROVED!


#CONCLUSION

In the activity performed about Matrix Operations, the students were able to
understand and know all of the Matrix Operations, which are Transposition, Determinant,
Inverse, and the Dot Product/Inner Product, including its Rule 1 and Rule 2 that presents the
six multiplication properties. It can be inferred that the codes would not work if the proper
declaration for each matrix was not used. The students were also able to put all of their
learnings from using Google Colaboratory, Python programming, and solving of Matrix into
practice by creating their own sample matrices that show Matrix Operations, and completing
Task 1 which aims to make a matrices on the different multiplication properties. Thus, the
students clearly defined and explained the entire results made in Google Colaboratory, as well
as Task 1. Furthermore, after accomplishing Task 1, the students were possibly done six flow
charts that signify how they appropriately know the given task, Python programming, and the
six dot product properties. After meeting all of the objectives, the students were able to
discern and properly concluded the laboratory report.
