<a href="https://colab.research.google.com/github/andrheadennizecuyme/LinearAlgebra_2ndSem/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE
## Laboratory 4: Matrices

# Objectives

At the end of this activty student will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations. 
3. Program and translate matrix equations and operations using Python. 

# Discussion


In [3]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

# Matrices
 
The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them.


Let's say for example you have A and B as system of equation.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
   \begin{array}\
   w-2x+3y-4z \\
   3w-x-2y+z \\
   2w-x+3y-2z
   \end{array}
\right. $$


We could see that A is a system of 2 equation with 2 parameters. While, B is a system of 3 equations with 2 parameters. We can represent them as matrices as:

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C=\begin{bmatrix} 1 & -2 & 3 & 4 \\ 3 & -1 & -2 & 1 \\ 2 & -1 & 3 & -2\end{bmatrix}
$$



So assuming that you already discussed the fundamental representation of matrices, their types, and operations. 

# Declaring Matrices 

Just like our previous laboratory activity, we'll represent system of linear equations as a matrix. The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices. And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be represented just like the equation below. Whereas A is a matrix consisting of elements denoted by aij. Denoted by i is the number of rows in the matrix while j stands for the number of columns.
Do note that the size of a matrix is i x j.

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


We already gone over some of the types of matrices as vectors but we'll further discuss them in this laboratory activity. Since you already know how to describe vectors using shape, dimensions and size attributes, we'll use them to analyze these matrices.



In [9]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [12]:
## Declaring a 2 x 2 matrix
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [18]:
## Declaring a 2 x 3 matrix
A = np.array([
    [5, 1, 3],
    [4, 7, 8]
])
describe_mat(A)

Matrix:
[[5 1 3]
 [4 7 8]]

Shape:	(2, 3)
Rank:	2



In [17]:
## Declaring a 3 x 2 matrix
A = np.array([
    [7, 9],
    [3, 1],
    [6, 6]
])
describe_mat(A)

Matrix:
[[7 9]
 [3 1]
 [6 6]]

Shape:	(3, 2)
Rank:	2



In [21]:
H = np.array([9,8,7,6,5])
describe_mat(H)

Matrix:
[9 8 7 6 5]

Shape:	(5,)
Rank:	1



# Categorizing Matrices

There are several ways of classifying matrices. Once could be according to their shape and another is according to their element values. We'll try to go through them.



## According to Shapes

### Rows and Column Matrices
Row and column matrices are common in vector and matrix computations. They can also represent row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be l x j  and column matrices would be j x l .

In [53]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    [1, 3, 2]
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3, -4]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[[1 3 2]]

Shape:	(1, 3)
Rank:	2
Is Square: False

Matrix:
[[ 1  2  3 -4]]

Shape:	(1, 4)
Rank:	2
Is Square: False



In [48]:
## Declaring a Column Matrix

col_mat = np.array([
    [1000.00],
    [99999],
    [8877]
])
describe_mat(col_mat)

Matrix:
[[ 1000.]
 [99999.]
 [ 8877.]]

Shape:	(3, 1)
Rank:	2
Is Square: False



### Square Matrices

Square matrices are matrices that have the same row and column sizes. We could say a matrix is square if i = j. We can tweak our matrix descriptor function to determine square matrices.

In [32]:
def describe_mat(matrix):
  is_square = True if matrix.shape[0] == matrix.shape[1] else False
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [34]:
square_mat = np.array([
    [2, 4, 6],
    [3, 6, 9],
    [4, 8, 12]
])

non_square_mat = np.array([
    [1, 3, 9],
    [4, 7, 10]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[ 1  3  9]
 [ 4  7 10]]

Shape:	(2, 3)
Rank:	2
Is Square: False



## According to Element Values

### Null Matrix

A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [54]:
def describe_mat(matrix):
  if matrix.size > 0:
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
  else: 
    print('Matrix is Null')

In [55]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


### Zero Matrix

A Zero Matrix can be any rectangular matrix but with all elements having a value of 0.

In [59]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectanglar Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectanglar Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


### Ones Matrix

a Ones Matrix, just like Zero Matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.

In [61]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones ((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectanglar Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectanglar Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


### Diagonal Matrix

A Diagonal Matrix is a square matrix that has values only at the diagonal of the matrix.

In [62]:
np.array([
    [3,0,0],
    [0,0,4],
    [4,0,3]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1,n-1]

array([[3, 0, 0],
       [0, 0, 4],
       [4, 0, 3]])

In [64]:
d = np.diag([9, 8, 7, 6])
d.shape[0]  == d.shape[1]
d

array([[9, 0, 0, 0],
       [0, 8, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 6]])

### Identity Matrix

An Identity Matrix is a special diagonal matrix in which at the diagonal are ones.

In [65]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Upper Triangular Matrix

An Upper Triangular Matrix is a matrix that has no values below the diagonal.

In [69]:
np.array([
    [1,2,3,4],
    [9,9,-3,-1],
    [169,643,9,12],
    [4,88.00,94,85]
])

array([[  1.,   2.,   3.,   4.],
       [  9.,   9.,  -3.,  -1.],
       [169., 643.,   9.,  12.],
       [  4.,  88.,  94.,  85.]])

### Lower Triangular Matrix

An Lower Triangular Matrix is a matrix that has no values above the diagonal.

In [72]:
np.array([
    [1,0,0],
    [5,2,3],
    [6,9,7]
])

array([[1, 0, 0],
       [5, 2, 3],
       [6, 9, 7]])

# PRACTICE

1. Given the linear combination below, try to create a corresponding matrix representing it.


$$\theta = 5x + 3y - z$$


2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown.

In [71]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


In [70]:
H = np.tril(G)
H

NameError: ignored

# Matrix Algebra

## Addition

## Subtraction

## Element-Wise Multiplication

# ACTIVITY

## Task 1

Create a function named mat_desc() that througouhly describes a matrix, it should:

1. Displays the shape, size, and rank of the matrix.
2. Displays whether the matrix is square or non-square.
3. Displays whether the matrix is an empty matrix.
4. Displays if the matrix is an identity, ones, or zeros matrix

Use 3 sample matrices in which their shapes are not lower than (3,3). In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
## Function Area

In [ ]:
## Matrix Declarations


In [ ]:
## Test Areas

## Task 2 

Create a function named mat_operations() that takes in two matrices a input parameters it should:

1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
2. Returns the sum of the matrices.
3. Returns the differen of the matrices.
4. Returns the element-wise multiplication of the matrices.
5. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than (3,3). In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.